name: NoTell
main: awzaw\notell\Main
version: 1.1.4
api: [3.0.0]
load: POSTWORLD
author: awzaw
website: https://github.com/awzaw
commands:
 notell:
  description: "Toggle Tell Messages to player"
  usage: |-
      /notell
      /notell <player>
      /notell <player> <on|off>
      /notell opsend
      /notell opsend <on|off>
      /notell oprecv
      /notell oprecv <on|off>
  permission: notell
permissions:
  notell:
    description: "Allows Use of /notell"
    default: op